[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = false
optimizer_runs = 200
remappings = [
    "@aave/core-v3/=lib/aave-v3-core/"
  ]
evm_version = "berlin"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

